FIN_COMPONENT = "fin"
WING_COMPONENT = "wing"
COMPOSITE_COMPONENT = "composite"
SWEPT_COMPONENT = "swept"
SWEPT_COMPONENT_MULTI_FACE = "swept_multi_face"
REVOLVED_COMPONENT = "revolved"
CUBE = "cube"
SPHERE = "sphere"
